version: 2
notify:  
jobs:
  build:
    working_directory: ~/myproject
    docker:
      - image: ucreateit/laravel-pgsql:0.0.1
        environment:
        DATABASE_URL: postgres://ubuntu@localhost:5432/postgres
      - image: postgres:9.6.2
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - checkout
      - run:
          name: Install System Dependencies
          command: |
            sudo apt-get update && sudo apt-get -f install && sudo apt-get install wget      
      - run: 
          name: Install Composer
          command: |
            sudo composer self-update
            composer install --prefer-source --no-interaction --dev
      - run: bash .circleci/setup-heroku.sh
      - run:
         name: Unit Tests
         command: |
           ./vendor/phpunit/phpunit/phpunit
      - add_ssh_keys:
          fingerprints:
            - "b1:c9:ad:27:ba:c7:96:a6:c8:02:90:e7:d3:75:04:6f"
      - deploy:
          name: Deploy Master to Heroku
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                git push heroku master
            fi
